# Generated by Django 3.0.5 on 2021-06-13 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('keep_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keepapp',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2021, 6, 13, 11, 23, 1, 593864, tzinfo=utc)),
        ),
    ]
